# Generated by Django 3.2.7 on 2021-09-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('developer', models.CharField(max_length=30)),
                ('genres', models.ManyToManyField(blank=True, to='games.Genre')),
                ('likes', models.ManyToManyField(blank=True, to='users.Profile')),
            ],
        ),
    ]
