# Generated by Django 3.2.7 on 2021-09-15 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='users_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
            preserve_default=False,
        ),
    ]
