# Generated by Django 3.2.7 on 2021-09-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_users_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_of_rating',
            field=models.IntegerField(default=0),
        ),
    ]
