# Generated by Django 3.2.7 on 2021-09-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_game_num_of_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(default='default_game_image.png', upload_to='game_pics'),
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(default='default_game_thumbnail.png', upload_to='thumbnail_pics'),
        ),
    ]
