# Generated by Django 3.2.7 on 2021-10-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_of_likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
